const screens = {
  LANDING: 'LANDING',
  CREATE_NEW_ACCOUNT: 'CREATE_NEW_ACCOUNT',
  COMPONENTS: {
    TOP_BAR: {
      PAGINATION: 'COMPONENTS.TOP_BAR.PAGINATION',
      QUESTION_MARK: 'COMPONENTS.TOP_BAR.QUESTION_MARK',
    },
  },
};

export default screens;
