const screens = {
  LANDING: "LANDING",
  OTP: "OTP", // deprecated
  // LOGIN: "LOGIN", // is this used??
  WELCOME: "WELCOME",
  REQUEST_CODE: "REQUEST_CODE",
  VERIFY_CODE: "VERIFY_CODE",
  ENTER_EMAIL: "ENTER_EMAIL",
  ENTER_NAME: "ENTER_NAME",
  COMPONENTS: {
    TOP_BAR: {
      BACK_BUTTON: "COMPONENTS.TOP_BAR.BACK_BUTTON",
      PAGINATION: "COMPONENTS.TOP_BAR.PAGINATION",
      QUESTION_MARK: "COMPONENTS.TOP_BAR.QUESTION_MARK",
    },
  },
};

export default screens;
